### ISSUE TITLE
Do not overwrite the field name deteled_at.

### ISSUE THREAD

**Issue by martinmurciego** [bsiddiqui/bookshelf-paranoia#20]
Specifying in this line the time stamp field for deletion
`bookshelf.plugin(require('bookshelf-paranoia'), { field: 'deletedat' })`
I had to change it in the source code to work. Otherwise it gave me error.

{
  "name": "error",
  "length": 126,
  "severity": "ERROR",
  "code": "42703",
  "position": "23",
  "file": "analyze.c",
  "line": "2163",
  "routine": "transformUpdateTargetList"
}

And running this code on my controller:
`destroyWithParanoia: function destroy(req, res) {
      //paranoia plugin externo de borrado logico
    return ( usuarioModel.forge('id', req.params.id).destroy()) // throws NoRowsDeletedError if no rows affected
      .then(function () {
        //Funciona pero no guarda en JSON el registro eliminado
        res.status(201).json({error: false, eliminado:registro});
        console.log("\nlos datos fueron eliminados!!!\n");
      }).catch(function (err) {
        res.status(400).json(err);
      })
  }`

**Comment by martinmurciego** [comment]
I have not used yield because it gives me error, but running the previous code I checked that the time stamp is set with the current date / time.
I am using Postgres 9.5 with timestamp fields without timezone.
Node 6.9.5, Express 4.13.4 and Bookshelf.js 0.10.3

**Comment by alanhoff** [comment]
@martinmurciego could you send your model declaration?
