### ISSUE TITLE
NoRowsDeletedError not thrown on model with deletion field already set

### ISSUE THREAD

**Issue by jadengore** [bsiddiqui/bookshelf-paranoia#24]
If a model has already been previously soft-deleted, and you try to delete the model again, a `NoRowsDeletedError` is not thrown. It is instead registered as a successful operation and updates the deleted field accordingly.

There needs to be a check on update to make sure that the record has not been previously deleted. I'm working on a PR to demonstrate/fix the error.

**Comment by alanhoff** [comment]
@jadengore We'll need more info on how to reproduce this error. I added a test and it successfully thrown the correct error https://github.com/estate/bookshelf-paranoia/pull/25

**Comment by jadengore** [comment]
@alanhoff It may be because I'm using PostgreSQL and they have different behavior at the `knex.update` spec. I'll do some more research and get back to you.
