### ISSUE TITLE
The default value can not be set to NULL and is set to "0000-00-00 00:00:00" instead.

### ISSUE THREAD

**Issue by HazemElAgaty** [bsiddiqui/bookshelf-paranoia#31]
I am using MySQL 5.6.35 (MAMP). When i tried to fetch records from the database, supposedly it should fetch all the undeleted data, however all data was fetched and the reason was that the "deleted_at" default value was "0000-00-00 00:00:00" instead of NULL. 

I have tried to set the default to null "table.timestamp("deleted_at").defaultTo(null);" and even "table.timestamp("deleted_at").defaultTo(knex.schema.raw("NULL"));" but the database throws an Invalid default value error. I tried to solve that by changing the sql_mode but nothing helps.

My question is how can I  change the "WHERE deleted_at IS NULL" to "WHERE deleted_at IS 0000-00-00 00:00:00" .

To be noted, the same project with the same knex migrations works fine on another machine with mysql version 5.7.

**Comment by HazemElAgaty** [comment]
Update: I solved the problem by changing the skipDeleted() function. Now it looks like this: 
`  function skipDeleted(model, attrs, options) {
    if (!options.isEager || options.parentResponse) {
      let softDelete = this.model
        ? this.model.prototype.softDelete
        : this.softDelete;

      if (softDelete && !options.withDeleted) {
        options.query
          .where(
            `${result(this, "tableName")}.${settings.field}`,
            "0000-00-00 00:00:00"
          )
          .orWhere(`${result(this, "tableName")}.${settings.field}`, null);
      }
    }
  }`

**Comment by bsiddiqui** [comment]
@HazemElAgaty yeah I think that could be configured as a option on the model

something like `fieldDefaultValue`, defaulting to null

**Comment by HazemElAgaty** [comment]
I tried to make a pull request with the fix but the problem is that your tests fail with an error.

**Comment by bsiddiqui** [comment]
@HazemElAgaty I can't see the error on circle since you didn't make a PR. Mind making the PR so I can see what's failing?
