### ISSUE TITLE
Using `Model.fetchAll()` calls `skipDeleted` twice while fetching

### ISSUE THREAD

**Issue by thezanke** [bsiddiqui/bookshelf-paranoia#32]
## Expected Behavior

Calling `Model.fetchAll()` to fetch a collection only adds the deleted_at condition once.
```sql
select "table".* from "table" where "table"."deleted_at" is null
```

## Actual Behavior

Calling `Model.fetchAll()`, the outputted SQL has the deleted_at condition repeated twice:
```sql
select "table".* from "table" where "table"."deleted_at" is null and "table"."deleted_at" is null
```

## Steps to Reproduce the Problem

  1. call `Model.fetchAll()` on a model that is marked as `softDelete: true`
  2. inspect the sql coming out of knex (I discovered while using mockKnex to write unit tests for some of my code)

## Specifications

  - bookshelf-paranoia version: `0.11.0`
  - bookshelf version: `0.12.0`
  - knex client: `pg`

## Possible Solution

I was able to fix this issue by removing the following line:

https://github.com/bsiddiqui/bookshelf-paranoia/blob/c831027e2d0c8b5fea115f30a7cbeabb8b1ac395/index.js#L78

This line seems to bind to collection fetching even though we are already binding to that on line 61. I think this line can be removed (or line 61) but I don't know enough about the implementation to know if that'd have negative effects on other parts of the library (or a different db driver).

**Comment by bsiddiqui** [comment]
Fixed by https://github.com/bsiddiqui/bookshelf-paranoia/pull/29
